"""iter2: subjects score_rules homeworks shop items + students.points + behaviors.score_rule_id

Revision ID: 04ede491dff6
Revises: c754234c1734
Create Date: 2026-05-01 23:10:28.883923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ede491dff6'
down_revision: Union[str, Sequence[str], None] = 'c754234c1734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('effect_hunger', sa.Integer(), nullable=False),
    sa.Column('effect_mood', sa.Integer(), nullable=False),
    sa.Column('consumable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'label', name='uq_rule_teacher_label')
    )
    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_rules_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_subject_teacher_name')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('homeworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homeworks_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homeworks_subject_id'), ['subject_id'], unique=False)

    op.create_table('homework_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id', name='uq_record_homework_student')
    )
    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_records_homework_id'), ['homework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_records_student_id'), ['student_id'], unique=False)

    op.create_table('pet_owned_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_owned_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_owned_items_pet_id'), ['pet_id'], unique=False)

    with op.batch_alter_table('behaviors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_behaviors_score_rule_id', 'score_rules',
            ['score_rule_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('students', schema=None) as batch_op:
        # 已有数据兼容：加 server_default='0'，避免 NOT NULL 失败
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # 预置商品（系统全局，所有老师共享）
    shop_items_table = sa.table(
        'shop_items',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('item_type', sa.String),
        sa.column('price', sa.Integer),
        sa.column('icon', sa.String),
        sa.column('description', sa.String),
        sa.column('effect_hunger', sa.Integer),
        sa.column('effect_mood', sa.Integer),
        sa.column('consumable', sa.Boolean),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(shop_items_table, [
        # 食品（消耗品，吃完恢复 hunger/mood）
        {'name': '苹果', 'item_type': '食品', 'price': 10, 'icon': '🍎', 'description': '清甜可口的苹果',
         'effect_hunger': 5, 'effect_mood': 0, 'consumable': True, 'sort_order': 1},
        {'name': '胡萝卜', 'item_type': '食品', 'price': 15, 'icon': '🥕', 'description': '宠物最爱',
         'effect_hunger': 10, 'effect_mood': 0, 'consumable': True, 'sort_order': 2},
        {'name': '蛋糕', 'item_type': '食品', 'price': 30, 'icon': '🍰', 'description': '吃了心情愉悦',
         'effect_hunger': 20, 'effect_mood': 5, 'consumable': True, 'sort_order': 3},
        {'name': '大餐', 'item_type': '食品', 'price': 50, 'icon': '🍖', 'description': '丰盛大餐，效果显著',
         'effect_hunger': 30, 'effect_mood': 5, 'consumable': True, 'sort_order': 4},
        # 衣服（可装备，仅装饰）
        {'name': '蝴蝶结', 'item_type': '衣服', 'price': 30, 'icon': '🎀', 'description': '可爱的蝴蝶结',
         'effect_hunger': 0, 'effect_mood': 0, 'consumable': False, 'sort_order': 11},
        {'name': '围巾', 'item_type': '衣服', 'price': 40, 'icon': '🧣', 'description': '保暖又时尚',
         'effect_hunger': 0, 'effect_mood': 0, 'consumable': False, 'sort_order': 12},
        {'name': '礼帽', 'item_type': '衣服', 'price': 50, 'icon': '🎩', 'description': '绅士风度',
         'effect_hunger': 0, 'effect_mood': 0, 'consumable': False, 'sort_order': 13},
        {'name': '墨镜', 'item_type': '衣服', 'price': 60, 'icon': '🕶️', 'description': '酷酷的造型',
         'effect_hunger': 0, 'effect_mood': 0, 'consumable': False, 'sort_order': 14},
        {'name': '皇冠', 'item_type': '衣服', 'price': 200, 'icon': '👑', 'description': '尊贵的象征',
         'effect_hunger': 0, 'effect_mood': 0, 'consumable': False, 'sort_order': 15},
        # 玩具（消耗品，使用后增加 mood）
        {'name': '小球', 'item_type': '玩具', 'price': 20, 'icon': '⚽', 'description': '玩耍专用',
         'effect_hunger': 0, 'effect_mood': 10, 'consumable': True, 'sort_order': 21},
        {'name': '玩偶', 'item_type': '玩具', 'price': 40, 'icon': '🧸', 'description': '柔软的伙伴',
         'effect_hunger': 0, 'effect_mood': 20, 'consumable': True, 'sort_order': 22},
        {'name': '游戏机', 'item_type': '玩具', 'price': 100, 'icon': '🎮', 'description': '欢乐时光',
         'effect_hunger': 0, 'effect_mood': 40, 'consumable': True, 'sort_order': 23},
    ])

    # 给已有老师补一份默认积分规则（新老师注册时由 auth.py 单独复制一份）
    score_rules_table = sa.table(
        'score_rules',
        sa.column('teacher_id', sa.Integer),
        sa.column('label', sa.String),
        sa.column('category', sa.String),
        sa.column('score', sa.Integer),
        sa.column('sort_order', sa.Integer),
        sa.column('active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
    )
    from datetime import datetime
    now = datetime.utcnow()
    default_rules = [
        ('回答问题', '学习', 1, 1),
        ('举手发言', '积极', 2, 2),
        ('按时完成', '学习', 3, 3),
        ('热心助人', '积极', 4, 4),
        ('作业优秀', '学习', 5, 5),
        ('迟到', '纪律', -2, 11),
        ('违纪', '纪律', -3, 12),
        ('不交作业', '学习', -4, 13),
        ('扰乱课堂', '纪律', -5, 14),
    ]
    conn = op.get_bind()
    teacher_ids = [r[0] for r in conn.execute(sa.text("SELECT id FROM teachers")).fetchall()]
    if teacher_ids:
        rows = []
        for tid in teacher_ids:
            for label, category, score, order in default_rules:
                rows.append({
                    'teacher_id': tid, 'label': label, 'category': category,
                    'score': score, 'sort_order': order, 'active': True, 'created_at': now,
                })
        op.bulk_insert(score_rules_table, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('behaviors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_behaviors_score_rule_id', type_='foreignkey')
        batch_op.drop_column('score_rule_id')

    with op.batch_alter_table('pet_owned_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_owned_items_pet_id'))

    op.drop_table('pet_owned_items')
    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_homework_records_homework_id'))

    op.drop_table('homework_records')
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homeworks_subject_id'))
        batch_op.drop_index(batch_op.f('ix_homeworks_class_id'))

    op.drop_table('homeworks')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_teacher_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('score_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_rules_teacher_id'))

    op.drop_table('score_rules')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
