"""homework type + correction fields

Revision ID: 2f91651af525
Revises: 95f48e1bb9f1
Create Date: 2026-05-02 21:07:27.620320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f91651af525'
down_revision: Union[str, Sequence[str], None] = '95f48e1bb9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_correction', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('corrected', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('corrected_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False, server_default='homework'))
        batch_op.create_index(batch_op.f('ix_homeworks_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homeworks_type'))
        batch_op.drop_column('type')

    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.drop_column('corrected_at')
        batch_op.drop_column('corrected')
        batch_op.drop_column('needs_correction')

    # ### end Alembic commands ###
