"""add pet_species and assets

Revision ID: b38c3ba0c167
Revises: 2f91651af525
Create Date: 2026-05-03 01:03:31.816010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38c3ba0c167'
down_revision: Union[str, Sequence[str], None] = '2f91651af525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pet_species_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', 'level', name='uq_species_level')
    )
    with op.batch_alter_table('pet_species_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_species_assets_species_id'), ['species_id'], unique=False)

    op.drop_table('_alembic_tmp_homework_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_homework_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('homework_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=500), nullable=False),
    sa.Column('scored_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('needs_correction', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('corrected', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('corrected_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id', name=op.f('uq_record_homework_student'))
    )
    with op.batch_alter_table('pet_species_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_species_assets_species_id'))

    op.drop_table('pet_species_assets')
    op.drop_table('pet_species')
    # ### end Alembic commands ###
